### PR TITLE
Avoid "Unknown report extention" and default to report.json

### PR DESCRIPTION
**Pull request by morucci**

### CODE REVIEW

**Comment by morucci** [comment]
There is probably a far better way to handle this. Just pushing here to hear about your suggestions.

**Comment by TristanCacqueray** [comment]
Thanks, it is indeed annoying to get that error. I would suggest to use the following data types:

```rust
enum ReportFormat {JSON, BINARY}
struct ReportRequest {
  path: PathBuf,
  open: bool,
  format: ReportFormat
}
```

And use that instead of the current `(&PathBuf, bool)` argument. That way we can parse the format early on and avoid the error/default format.

**Comment by TristanCacqueray** [comment]
Actually `open` is not relevant here because we can always serve a report without writing it to disk. See #127

**Comment by morucci** [comment]
That could be a followup to #132 132

**Comment by TristanCacqueray** [comment]
This is now implemented in #132

**Pull request closed without merging**
